# ---------- DATABASE ----------
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/task_management}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:SunUser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:SunlessGrey}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ---------- JPA ----------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

# ---------- JACKSON ----------
spring.jackson.deserialization.fail-on-unknown-properties=true

server.port=${SPRING_DOCKER_PORT:8080}

# ---------- LIQUIBASE ----------
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:changelog/db.changelog-master.yaml

# ---------- DROPBOX ----------
dropbox.access.token=${DROPBOX_ACCESS_TOKEN}
dropbox.upload.url=https://content.dropboxapi.com/2/files/upload
dropbox.download.url=https://content.dropboxapi.com/2/files/download
dropbox.delete.url=https://api.dropboxapi.com/2/files/delete_v2

jwt.expiration=300000
jwt.secret=helloworld12341241231243215grwg13f421
