spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
dropbox.access.token=${DROPBOX_ACCESS_TOKEN}
dropbox.upload.url=https://content.dropboxapi.com/2/files/upload
dropbox.download.url=https://content.dropboxapi.com/2/files/download
dropbox.delete.url=https://api.dropboxapi.com/2/files/delete_v2

