spring.datasource.url=jdbc:mysql://${MYSQLDB_HOST:localhost}:${MYSQLDB_LOCAL_PORT:3306}/\
${MYSQLDB_DATABASE:taskmanagement}
spring.datasource.username=${MYSQLDB_USER:root}
spring.datasource.password=${MYSQLDB_ROOT_PASSWORD:SunlessGrey0706}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jackson.deserialization.fail-on-unknown-properties=true
server.servlet.context-path=/api
spring.liquibase.enabled=true

dropbox.access.token=${DROPBOX_ACCESS_TOKEN}
dropbox.upload.url=https://content.dropboxapi.com/2/files/upload
dropbox.download.url=https://content.dropboxapi.com/2/files/download
dropbox.delete.url=https://api.dropboxapi.com/2/files/delete_v2
